name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
    
      - name: Checkout repository
        if: steps.release.outputs.release_created == 'true'
        uses: actions/checkout@v4
      
      - name: Set up Python
        if: steps.release.outputs.release_created == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        if: steps.release.outputs.release_created == 'true'
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Build artifacts
        if: steps.release.outputs.release_created == 'true'
        run: |
          poetry install --no-interaction --no-root
          poetry build
      
      - name: Upload Release Assets
        if: steps.release.outputs.release_created == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
